version: "3"
services:
  wiremock:
    image: "holomekc/wiremock-gui:latest"
    container_name: wiremock-gui
    user: root
    ports:
      - "8089:8089"
    volumes: 
      - wiremock-storage-vol:/home/wiremock/storage
    environment:
      WIREMOCK_OPTIONS: "--port=8089,--https-port=8088,--max-request-journal=1000,--local-response-templating,--root-dir=/home/wiremock/storage"
volumes:
  wiremock-storage-vol:
    driver: local